"""OKF concept data model.

A :class:`Concept` keeps the full frontmatter mapping (so unknown producer keys
are preserved, per the OKF permissive-consumption rule) plus typed convenience
accessors for the fields VesnAI cares about.
"""

from __future__ import annotations

import re
from dataclasses import dataclass, field
from enum import Enum
from typing import Any

# Reserved filenames per OKF v0.1 - they have special structural meaning and are
# not required to carry a `type`.
RESERVED_FILENAMES = frozenset({"index.md", "log.md"})

# Recommended frontmatter keys, in OKF priority order. Used to keep a stable,
# readable key ordering when serializing.
RECOMMENDED_ORDER = ("type", "title", "description", "resource", "tags", "timestamp")

_MARKDOWN_LINK = re.compile(r"\[(?P<text>[^\]]*)\]\((?P<href>[^)]+)\)")


class Origin(str, Enum):
    """Whether a concept was authored by the user or generated by VesnAI."""

    USER = "user"
    GENERATED = "generated"


@dataclass
class Concept:
    """A single OKF concept: frontmatter mapping + Markdown body.

    The ``frontmatter`` dict is the source of truth and preserves unknown keys.
    Typed properties below read/write well-known keys within it.
    """

    frontmatter: dict[str, Any] = field(default_factory=dict)
    body: str = ""

    # ------------------------------------------------------------------ #
    # Well-known OKF fields
    # ------------------------------------------------------------------ #
    @property
    def type(self) -> str | None:
        value = self.frontmatter.get("type")
        return str(value) if value is not None else None

    @type.setter
    def type(self, value: str) -> None:
        self.frontmatter["type"] = value

    @property
    def title(self) -> str | None:
        value = self.frontmatter.get("title")
        return str(value) if value is not None else None

    @property
    def description(self) -> str | None:
        value = self.frontmatter.get("description")
        return str(value) if value is not None else None

    @property
    def tags(self) -> list[str]:
        value = self.frontmatter.get("tags")
        if value is None:
            return []
        if isinstance(value, str):
            return [value]
        return [str(v) for v in value]

    @tags.setter
    def tags(self, value: list[str]) -> None:
        self.frontmatter["tags"] = list(value)

    @property
    def timestamp(self) -> str | None:
        value = self.frontmatter.get("timestamp")
        return str(value) if value is not None else None

    # ------------------------------------------------------------------ #
    # VesnAI profile fields (namespaced under the `vesnai` key)
    # ------------------------------------------------------------------ #
    @property
    def vesnai(self) -> dict[str, Any]:
        ns = self.frontmatter.get("vesnai")
        if not isinstance(ns, dict):
            ns = {}
            self.frontmatter["vesnai"] = ns
        return ns

    @property
    def origin(self) -> Origin:
        raw = self.vesnai.get("origin", Origin.USER.value)
        try:
            return Origin(raw)
        except ValueError:
            return Origin.USER

    @origin.setter
    def origin(self, value: Origin | str) -> None:
        self.vesnai["origin"] = value.value if isinstance(value, Origin) else str(value)

    @property
    def note_id(self) -> str | None:
        value = self.vesnai.get("id")
        return str(value) if value is not None else None

    @property
    def source(self) -> str | None:
        """Relative path of the concept this one was generated from, if any."""
        value = self.vesnai.get("source")
        return str(value) if value is not None else None

    @property
    def is_generated(self) -> bool:
        return self.origin is Origin.GENERATED

    @property
    def done(self) -> bool:
        """User marked this note as done (excluded from review resurfacing)."""
        return bool(self.vesnai.get("done", False))

    @done.setter
    def done(self, value: bool) -> None:
        self.vesnai["done"] = bool(value)

    @property
    def done_at(self) -> str | None:
        value = self.vesnai.get("done_at")
        return str(value) if value is not None else None

    # ------------------------------------------------------------------ #
    # Links
    # ------------------------------------------------------------------ #
    def body_links(self) -> list[str]:
        """Return the hrefs of all Markdown links found in the body."""
        return [m.group("href") for m in _MARKDOWN_LINK.finditer(self.body)]

    def explicit_links(self) -> list[str]:
        """Links from `vesnai.links` frontmatter. These are bundle-root-relative."""
        explicit = self.vesnai.get("links") or []
        if isinstance(explicit, str):
            explicit = [explicit]
        return [str(x) for x in explicit]

    def links(self) -> list[str]:
        """All outgoing links (raw): explicit `vesnai.links` plus body Markdown links.

        Note: explicit links are bundle-root-relative while body links are
        file-relative; use :func:`vesnai.okf.conformance.resolve_link` to resolve
        each to a canonical bundle path.
        """
        ordered: list[str] = list(self.explicit_links())
        for href in self.body_links():
            if href not in ordered:
                ordered.append(href)
        return ordered
